#!/bin/bash

#Aliai
alias ll='ls -lh'
alias la='ls -lah'
alias gitter='git clone'
alias weather='curl wttr.in/~mannheim-germany'
alias moon="curl wttr.in/Moon"
alias gcr='git commit -am "gem:0 rebase"'
alias bach="echo \"I got you boi, bash comin' right up\";bash"
alias gfy='git fetch --all --prune'
alias ccat='pygmentize -g'
alias subli3='subl ~/.config/i3/'
alias cdx='cd /home/tballast/git/reportix/xbrl-server2'
alias mkdirdate="mkdir $(date '+%d-%b-%Y')"
alias sshlordsugar="ssh -i ~/.ssh/id_rsa_reportix_server tballast@lord-sugar"

alias rmdeadcont="docker rm $(docker ps -aq --filter status=exited)"


alias stressme50='stress --cpu 4 --timeout 5'
alias stressme100='stress --cpu 8 --timeout 5'
alias stressme25='stress --cpu 2 --timeout 5'


#Environment
export JAVA_HOME="/usr/lib/jvm/java-11-oracle"

export PATH=$PATH:$JAVA_HOME
export PATH=$PATH:~/scripts/sys
export PATH=$PATH:/home/tballast/bin
export PATH=$PATH:/home/tballast/bin/sloppz
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/opt/ti/ccsv7/eclipse
export PATH=$PATH:~/bin
export PATH=$PATH:/opt/sts-bundle/sts-3.9.4.RELEASE
export PATH=$PATH:/opt/idea-IU-183.4284.148/bin
export PATH=$PATH:/opt/WebStorm-183.5912.23/bin
export PATH=$PATH:/opt/idea-IU-191.6183.87/bin

export PATH=~/.local/bin:$PATH
export GEM_HOME=$HOME/gems
export PATH=$PATH:$GEM_HOME/bin

export NVM_SYMLINK_CURRENT=true
#export PATH=$PATH:/home/tballast/hlfabric/fabric-samples/bin
export PATH=$PATH:/home/tballast/fabric/fabric-samples-1.4/bin

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:`yarn global bin`

export MANPATH="$MANPATH:/usr/local/arm-linux-4.4.2/man"

alias gnome-control-center="XDG_CURRENT_DESKTOP=Unity gnome-control-center"

if which kubectl > /dev/null  ; then
    source <(kubectl completion zsh)
fi

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#Functions
function preexec() {
	tmr=$(($(date +%s%N)/1000000))
}

function precmd() {
	if [ $tmr ]; then
		jetzt=$(($(date +%s%N)/1000000))
		elapsed=$(($jetzt-$tmr))

		# Need to grab the elapsed seconds ans elapsed milliseconds. 

		SEC=1000
		MIN=60000
		HOUR=3600000
		DAY=86400000

		num_days=$(expr $elapsed / $DAY)
		num_hours=$(expr $elapsed % $DAY / $HOUR)
		num_mins=$(expr $elapsed % $HOUR / $MIN)
		num_secs=$(expr $elapsed % $MIN / $SEC)
		num_millis=$(expr $elapsed % $SEC)
		time_str=""

		# Only add Days, Hours, and Minutes if they are actually necessary
		if [ $num_days -gt 0 ]; then
			time_str=${time_str}${num_days}"d "
		fi
		if [ $num_hours -gt 0 ]; then
			time_str=${time_str}${num_hours}"h "
		fi
		if [ $num_mins -gt 0 ]; then
			time_str=${time_str}${num_mins}"m "
		fi

		# Format the milliseconds with 3 decimal places
		millis_pretty=$(printf '%03d' $num_millis)

		time_str=${time_str}${num_secs}"s"${millis_pretty}

		export RPROMPT="%F{cyan}[${time_str}] %{$reset_color%}"
		unset tmr
	fi

	echo -ne `pwd` > /tmp/SHIT

}

setopt HIST_IGNORE_SPACE


# Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


#source ~/.zprofile
