
setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=1000
HISTFILE=~/.zsh_history

source /home/tballast/antigen/antigen.zsh

antigen use oh-my-zsh

# Bundle in some plugins
antigen bundle common-aliases
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen theme ys

antigen apply

# Going inside a docker container
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

goinside(){
    docker exec -it $1 bash -c "stty cols $COLUMNS rows $LINES && bash";
};
_goinside(){
    COMPREPLY=( $(docker ps --format "{{.Names}}" -f name=$2) );
};

complete -F _goinside goinside;
export goinside;

#Get My aliases and stuff
source ~/.tball_custom_zsh
